package com.example.sharding_jdbc_demo3.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.order_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.user_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.order_id
     *
     * @return the value of t_order_1.order_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.order_id
     *
     * @param orderId the value for t_order_1.order_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.user_id
     *
     * @return the value of t_order_1.user_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.user_id
     *
     * @param userId the value for t_order_1.user_id
     *
     * @mbg.generated Wed Oct 13 15:53:10 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}