package com.example.my_distribute_lock.dao;

import com.example.my_distribute_lock.model.DistributeLock;
import com.example.my_distribute_lock.model.DistributeLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistributeLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    long countByExample(DistributeLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int deleteByExample(DistributeLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int insert(DistributeLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int insertSelective(DistributeLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    List<DistributeLock> selectByExample(DistributeLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    DistributeLock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int updateByExampleSelective(@Param("record") DistributeLock record, @Param("example") DistributeLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int updateByExample(@Param("record") DistributeLock record, @Param("example") DistributeLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int updateByPrimaryKeySelective(DistributeLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    int updateByPrimaryKey(DistributeLock record);

    
    //businessCode是用来区分这个锁是锁的哪个业务，比如这里锁的是订单业务
    DistributeLock selectDistributeLock(@Param("businessCode") String businessCode);
}
