package com.example.my_distribute_lock.model;

public class DistributeLock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribute_lock.id
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribute_lock.bussiness_code
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    private String bussinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribute_lock.bussinee_name
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    private String bussineeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribute_lock.id
     *
     * @return the value of distribute_lock.id
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribute_lock.id
     *
     * @param id the value for distribute_lock.id
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribute_lock.bussiness_code
     *
     * @return the value of distribute_lock.bussiness_code
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public String getBussinessCode() {
        return bussinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribute_lock.bussiness_code
     *
     * @param bussinessCode the value for distribute_lock.bussiness_code
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public void setBussinessCode(String bussinessCode) {
        this.bussinessCode = bussinessCode == null ? null : bussinessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribute_lock.bussinee_name
     *
     * @return the value of distribute_lock.bussinee_name
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public String getBussineeName() {
        return bussineeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribute_lock.bussinee_name
     *
     * @param bussineeName the value for distribute_lock.bussinee_name
     *
     * @mbg.generated Thu Sep 23 16:27:24 CST 2021
     */
    public void setBussineeName(String bussineeName) {
        this.bussineeName = bussineeName == null ? null : bussineeName.trim();
    }
}